change vagrant up command and added debug task

diff --git a/.github/workflows/ansible_playbooks/ova_generator.yaml b/.github/workflows/ansible_playbooks/ova_generator.yaml
--- a/.github/workflows/ansible_playbooks/ova_generator.yaml
+++ b/.github/workflows/ansible_playbooks/ova_generator.yaml
@@ -114,15 +114,43 @@
         executable: /bin/bash
       become: true
 
-    - name: Deploy the VM using Vagrant
-      shell: "vagrant up"
+    # - name: Deploy the VM using Vagrant
+    #   shell: "vagrant up"
+    #   args:
+    #     chdir: "/tmp/wazuh-virtual-machines/ova/workflow_assets"
+    #   retries: 20
+    #   delay: 30
+    #   until: result.rc == 0
+    #   become: true
+
+    - name: Run vagrant up 
+      shell: |
+        #!/bin/bash
+        MAX_RETRIES=20
+        attempts=0
+        cd /tmp/wazuh-virtual-machines/ova/workflow_assets
+        while true; do
+          ((attempts++))
+          if vagrant up; then
+            break
+          else
+            if [ $attempts -eq $MAX_RETRIES ]; then
+              echo "Max attempts reached"
+              exit 1
+            fi
+            vagrant destroy -f
+          fi
+        done
       args:
-        chdir: "/tmp/wazuh-virtual-machines/ova/workflow_assets"
-      retries: 20
-      delay: 30
-      until: result.rc == 0
+        executable: /bin/bash
+      register: vagrant_up_result
       become: true
-    
+
+    - name: Show the result of the vagrant up command
+      debug:
+        var: vagrant_up_result
+        verbosity: 2
+
     - name: Execute Python script in the VM
       shell: "vagrant ssh -c 'sudo python3 /tmp/ova_directory/ova_configurer.py --wia_branch {{ wia_branch }} --repository {{ repository }} --debug {{ debug}}'"
       args:
