redesing vagrant up task

diff --git a/.github/workflows/ansible_playbooks/ova_generator.yaml b/.github/workflows/ansible_playbooks/ova_generator.yaml
--- a/.github/workflows/ansible_playbooks/ova_generator.yaml
+++ b/.github/workflows/ansible_playbooks/ova_generator.yaml
@@ -110,8 +110,26 @@
             vagrant destroy -f $id
           done
         fi
+        MAX_RETRIES=30
+        attempts=0
+        cd /tmp/wazuh-virtual-machines/ova/workflow_assets
+        while true; do
+          ((attempts++))
+          echo "Attempt: $attempts" >&2
+          if vagrant up; then
+            echo "vagrant up complete in attempt: $attempts" >&2
+            break
+          else
+            if [ $attempts -eq $MAX_RETRIES ]; then
+              echo "Max attempts reached" >&2
+              exit 1
+            fi
+            vagrant destroy -f
+          fi
+        done
       args:
         executable: /bin/bash
+      register: vagrant_up_result
       become: true
 
     # - name: Deploy the VM using Vagrant
@@ -123,37 +141,36 @@
     #   until: result.rc == 0
     #   become: true
 
-    - name: Attempt to run vagrant up
-      block:
-        - name: Run vagrant up 
-          shell: |
-            #!/bin/bash
-            MAX_RETRIES=30
-            attempts=0
-            cd /tmp/wazuh-virtual-machines/ova/workflow_assets
-            while true; do
-              ((attempts++))
-              echo "Attempt $attempts"
-              if vagrant up; then
-                break
-              else
-                if [ $attempts -eq $MAX_RETRIES ]; then
-                  echo "Max attempts reached"
-                  exit 1
-                fi
-                vagrant destroy -f
-              fi
-            done
-          args:
-            executable: /bin/bash
-          register: vagrant_up_result
-          become: true
+    # - name: Attempt to run vagrant up
+    #   block:
+    #     - name: Run vagrant up 
+    #       shell: |
+    #         #!/bin/bash
+    #         MAX_RETRIES=30
+    #         attempts=0
+    #         cd /tmp/wazuh-virtual-machines/ova/workflow_assets
+    #         while true; do
+    #           ((attempts++))
+    #           echo "Attempt $attempts"
+    #           if vagrant up; then
+    #             break
+    #           else
+    #             if [ $attempts -eq $MAX_RETRIES ]; then
+    #               echo "Max attempts reached"
+    #               exit 1
+    #             fi
+    #             vagrant destroy -f
+    #           fi
+    #         done
+    #       args:
+    #         executable: /bin/bash
+    #       register: vagrant_up_result
+    #       become: true
 
-      always:
-        - name: Show the result of the vagrant up command
-          debug:
-            var: vagrant_up_result
-            verbosity: 2
+    - name: Show the result of the vagrant up command
+      debug:
+        var: vagrant_up_result
+        verbosity: 2
 
     - name: Copy the Python script to the VM
       shell: |
